### ISSUE TITLE
show/search for similar ideas as you type a new one

### ISSUE THREAD

**Issue by goenning** [getfider/fider#257]
Source: https://feedback.fider.io/ideas/12/show-search-for-similar-ideas-as-you-type-a-new-one

##  Part 1

- [x]  Refactor current code, move 'showing' filter to QueryString and not hashtag
- [x] Create Search API using Postgres text search capabilities
- [x] Create migration to add postgres extension for similarity function
- [x] Change main page to use new search API (delay typing by 100ms?)

## Part 2

- [x] Apply filter while inserting a new idea so the user can see if there's an existing one or not
- [x] remove BasicIdea types, struct and methods and replace it with use Search?q=
